---
AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
AWS_SECRET_ACCESS_KEY: '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'
STITCH_QUEUE: "video-stitch"
FINISH_QUEUE: "video-stitch-ready"
BUCKET: "hollerback-app-dev"
