---
production:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch"
  FINISH_QUEUE: "video-stitch-ready"
  ERROR_SNS: "video-stitch-error"
  BUCKET: "hb-media"
  THREADS: 5
development:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch-dev"
  FINISH_QUEUE: "video-stitch-ready-dev"
  ERROR_SNS: "video-stitch-error-dev"
  BUCKET: "hb-media-dev"
  THREADS: 1
test:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch-dev"
  FINISH_QUEUE: "video-stitch-ready-dev"
  ERROR_SNS: "video-stitch-error-dev"
  BUCKET: "hb-media-dev"
  THREADS: 1
