---
production:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch"
  FINISH_QUEUE: "video-stitch-ready"
  ERROR_QUEUE: "video-stitch-error"
  BUCKET: "hollerback-app-dev"
development:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch-dev"
  FINISH_QUEUE: "video-stitch-ready-dev"
  ERROR_QUEUE: "video-stitch-error-dev"
  BUCKET: "hollerback-app-dev"
test:
  AWS_ACCESS_KEY_ID: 'AKIAJLG6CN7ONSGY6YXA'
  AWS_SECRET_ACCESS_KEY: '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'
  STITCH_QUEUE: "video-stitch-dev"
  FINISH_QUEUE: "video-stitch-ready-dev"
  ERROR_QUEUE: "video-stitch-error-dev"
  BUCKET: "hollerback-app-dev"
